run:
  timeout: "5m"

linters:
  disable-all: true
  enable: [
    "revive",
    "govet",
    "goimports",
    "gofmt",
    "gosec",
    "staticcheck",
  ]

linters-settings:
  goimports:
    local-prefixes: "github.com/metal3-io/baremetal-operator"
  govet:
    check-shadowing: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:"
  # Dot imports for gomega and ginkgo are allowed
  # within test files and test utils.
  - linters:
    - revive
    - stylecheck
    path: _test\.go
    text: should not use dot imports
  - linters:
    - revive
    - stylecheck
    path: (e2e)/.*.go
    text: should not use dot imports
